apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: repository
  interval: 10m
  path: ./common/manifests
  prune: true
  validation: client
