apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: repository
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/2kai/kubernetes-school
  ref:
    branch: master
